
// Rota Calendar

// findAllContracts 
###
GET http://localhost:3003/calendar/

// CreateClass
###
POST http://localhost:3003/calendar/
Content-Type: application/json 

{
    "name": "hatha",
    "date": "01/04/2022",
    "day": "Sexta-feira",
    "time": "19:00",
    "teacher": "Louize"
           
}

// editClass
###
PUT http://localhost:3003/calendar/5ab2bb1e-1624-4d0c-920e-7b5232515503
Content-Type: application/json 

{
    "name": "Yoga Restaurativo",
    "time": "07:00",
    "teacher": "Louize",
    "changingDate": "05/04/2022"
}

// deleteClass
// esse endpoint a data precisa vir diferente!!
###
DELETE http://localhost:3003/calendar/5ab2bb1e-1624-4d0c-920e-7b5232515503/05-04-2022
