// Rota Auth

// Login
### 
POST http://localhost:3003/auth/login
Content-Type: application/json

{
    "email": "rodrigobbuquera@gmail.com",
    "password": "123456"

}

# {
#     "email": "yogamangalasorocaba@gmail.com",
#     "password": "L0u@r0"

# }

// Rota Plan

// findAllPlans
###
GET http://localhost:3003/plans/list


/

// postPlan
###
POST http://localhost:3003/plans
Content-Type: application/json 

{
    "type": "Trimestral",
    "frequency": "3x",
    "availableClasses": 36,
    "durationInMonths": 3
}

// deletePlan
###
DELETE  http://localhost:3003/plans/planos


// Rota Contracts

// findAllContracts
###
GET http://localhost:3003/contracts/list

// createContract
###
POST http://localhost:3003/contracts/create
Content-Type: application/json 

{
    "email": "rodrigobbuquera@gmail.com",
    "name": "Rodrigo Brezolin Buquera",
    "plan": "1x-Semestral",
    "date": "20/03/2022"
           
}

// deleteContract
###
DELETE http://localhost:3003/contracts/ffcb7e80-9bc0-4262-bc29-4b02584ed95f


// findContractbyId
###
GET  http://localhost:3003/contracts/e315977f-a467-4875-86b4-a60bda2621b2

// findConstract - proprui
###
GET http://localhost:3003/contracts/user


// addNewContract
###
PUT http://localhost:3003/contracts/addNew/e315977f-a467-4875-86b4-a60bda2621b2
Content-Type: application/json 

{
    "plan": "1x-Mensal",
    "date": "05/04/2022"
           
}