// findAllPlans
###
GET http://localhost:3003/plans/list

// postPlan
###
POST http://localhost:3003/plans
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzczNTYyLCJleHAiOjE2NjE3NzcxNjJ9.h9ZkcCbIugsuCxc6m8noFCLvXSK8JgiUJPKzrL_PNfA
Content-Type: application/json 

{
    "type": "Semestral",
    "frequency": "3x",
    "availableClasses": 36,
    "durationInMonths": 3,
    "monthlyPayment": "R$ 199,00"
}

// editPlan
###
PUT http://localhost:3003/plans/3x-Semestral
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzczNTYyLCJleHAiOjE2NjE3NzcxNjJ9.h9ZkcCbIugsuCxc6m8noFCLvXSK8JgiUJPKzrL_PNfA
Content-Type: application/json 

{
    "type": "Semestral",
    "frequency": "3x",
    "availableClasses": 36,
    "durationInMonths": 3,
    "monthlyPayment": "R$ 160,00"
}

// deletePlan
###
DELETE  http://localhost:3003/plans/3x-Semestral
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzczNTYyLCJleHAiOjE2NjE3NzcxNjJ9.h9ZkcCbIugsuCxc6m8noFCLvXSK8JgiUJPKzrL_PNfA

