
// Rota Calendar

// findAllClasses
###
GET http://localhost:3003/calendar?today=true
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRQWUNqNzZ0QTRYQ0dyd05WYTB3ajd4ajR6MzMiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjU2MDc5OTExLCJleHAiOjE2NTYwODM1MTF9.oleoGpVWWTKGbMNaZWWNIMbLvThioVf1OvekKMvFg_A

// CreateClass
###
POST http://localhost:3003/calendar/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRQWUNqNzZ0QTRYQ0dyd05WYTB3ajd4ajR6MzMiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjU2NjA1Nzk3LCJleHAiOjE2NTY2MDkzOTd9.Rle_tUCOL_3gI0ETWrMX-aJPBaH_8I10WGUwEwN82SU
Content-Type: application/json 

{
    "name": "Hatha Yoga",
    "date": "30/06/2022",
    "day": "Quinta",
    "time": "19:00",
    "teacher": "Rodrigo"           
}

// editClass
###
PUT http://localhost:3003/calendar/5ab2bb1e-1624-4d0c-920e-7b5232515503
Content-Type: application/json 

{
    "name": "Yoga Restaurativo",
    "time": "07:00",
    "teacher": "Louize",
    "changingDate": "05/04/2022"
}

// deleteClass
// esse endpoint a data precisa vir diferente!! pois o params não aceita /
###
DELETE http://localhost:3003/calendar/ea500184-eef2-4b5c-9aa5-82100f3ec76f/01-01-2021
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRQWUNqNzZ0QTRYQ0dyd05WYTB3ajd4ajR6MzMiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjU2NTkzMTY0LCJleHAiOjE2NTY1OTY3NjR9.t9TAkZAX-XgUXnlZ_7R78pEZ4HUblms2IbJ48cdSaQ8