
// Rota Contracts

// findAllContracts
###
GET http://localhost:3003/contracts/list
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzNWQ5MmUwLTY3ZmEtNDcxZC05Njk4LWJlYThjNTVhMzFhMyIsImFkbWluIjpmYWxzZSwiaWF0IjoxNjc0MjMwODk3LCJleHAiOjE2NzQyMzQ0OTd9.qwGzpniEUC5R6H6RMO6Vn0iLVJIpmf2VO9JMRODtQkE
// createContract
###
POST http://localhost:3003/contracts
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxODU4OTcwLCJleHAiOjE2NjE4NjI1NzB9.iAeCU7E9vn_cwzjH8ug55w7oZMXYnNqzQQE4ZoYL-TA

{
    "email": "rodrigobbuquera2222@gmail.com",
    "name": "Rodrigo brezolin",
    "plan": "1x-Semestral",
    "date": "2022-03-01"
}

// deleteContract
###
DELETE http://localhost:3003/contracts/ffcb7e80-9bc0-4262-bc29-4b02584ed95f


// findContractbyId
###
GET  http://localhost:3003/contracts/e315977f-a467-4875-86b4-a60bda2621b2

// findConstract - proprui
###
GET http://localhost:3003/contracts/user


// addNewContract
###
PUT http://localhost:3003/contracts/addNew/1926d57b-904c-46df-ac80-2ff0346a35b4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxODU4OTcwLCJleHAiOjE2NjE4NjI1NzB9.iAeCU7E9vn_cwzjH8ug55w7oZMXYnNqzQQE4ZoYL-TA
Content-Type: application/json 

{
    "plan": "1x-Mensal",
    "date": "2023-01-01"       
}

// editContract
###
PUT http://localhost:3003/contracts/edit/1926d57b-904c-46df-ac80-2ff0346a35b4
Content-Type: application/json 

{
    "plan": "1x-Mensal",
    "date": "2023-01-07"       
}


// changeClasse
###
PUT http://localhost:3003/contracts/changeClasses/subtract/d35d92e0-67fa-471d-9698-bea8c55a31a3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzc3NTM2LCJleHAiOjE2NjE3ODExMzZ9.XHwcpiVGBEquH2BbZPNEEmSnfqEldc4yBZg2yV29Azw
