
// Rota Calendar

// findAllClasses
###
GET http://localhost:3003/calendar?today=true
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImViYzIwNzkzNTQ1NzExODNkNzFjZWJlZDI5YzU1YmVmMjdhZDJjY2IiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20veWdtLXRlc3RlcyIsImF1ZCI6InlnbS10ZXN0ZXMiLCJhdXRoX3RpbWUiOjE3MTEzODg5MzMsInVzZXJfaWQiOiJmeHNhRkNmT2toVWpJUks0WGdXMmdoNndiY2UyIiwic3ViIjoiZnhzYUZDZk9raFVqSVJLNFhnVzJnaDZ3YmNlMiIsImlhdCI6MTcxMTM4ODkzMywiZXhwIjoxNzExMzkyNTMzLCJlbWFpbCI6ImFkbWludGVzdEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYWRtaW50ZXN0QGVtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.BiKG7zmLiMqzUNAeYvYOq7x9cpxjO8XR5fBF5fM9yekpkGD2LNh_EkNqI0mxaPSr9UoBX_IgF4jqg3MsKBvj1rZz5-w7xvD5qBj9wPyjkGtU8M00F1RLk5jBSYVz9agG4C-ZInWkqxeXm7bui3fCYJnmwRqqXQFOL-RPi67cfxVMB0C146zyOJ2x8LAmNByiigLA9c3bbUFX2t25VbUnW2WpCEYuuyyC9bYUrFDyK9R-91GGqz_w4mk44sUxffYXXXFHnCwJtKUYLq7F2_NsdyCessV2L-YvGSK081WihvsPOcZVsB6aG5sU7LvOQgz9IG98saZdJE4eXC7HZEu4GQ
// CreateClass

###
POST http://localhost:3003/calendar/
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6IjlhNTE5MDc0NmU5M2JhZTI0OWIyYWE3YzJhYTRlMzA2M2UzNDFlYzciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20veWdtLXRlc3RlcyIsImF1ZCI6InlnbS10ZXN0ZXMiLCJhdXRoX3RpbWUiOjE2OTY0NjIyMDEsInVzZXJfaWQiOiJmeHNhRkNmT2toVWpJUks0WGdXMmdoNndiY2UyIiwic3ViIjoiZnhzYUZDZk9raFVqSVJLNFhnVzJnaDZ3YmNlMiIsImlhdCI6MTY5NjQ2MjIwMSwiZXhwIjoxNjk2NDY1ODAxLCJlbWFpbCI6ImFkbWludGVzdEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYWRtaW50ZXN0QGVtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.CPizxhRyeMRMdwgvl__6ZF33GJJFUbgr6in5rekM2Tv0PGZnp5TTT28klXa1h4TEKFyKyf58CiPhoexxXwPOOmYsv9HUJZkRlsvkywLwYLctkamURIIac10b9TDEgMWCkY0Tl4r1YSsK371lXf1SMmeJgfdz_aJcNpgzDeH6uIA88415a-XEXyZtbpnb_aASDMTxNCHsNfUtyIl0OnyBiuIb741NHcKW-w2m4C7n810JSaQRBy1trPHX6A95OdnYL0QH_gz-cXDYXkv08VXKax9nt4LM9idwNQqRKLkZSGAIlWnIreLCyWRlq-G1eXueK7-Nsxf1-BI858Azo4q3hw
Content-Type: application/json 

{
    "name": "Hatha Yoga",
    "date": "2022-10-06",
    "day": "Sexta",
    "time": "09:45",
    "capacity": 8,
    "teacher": "Rodrigo",
    "quantity": 1           
}

// editClass
###
PUT http://localhost:3003/calendar/e739d3e6-f966-4895-bf86-a2fd98bbb7f5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzY5OTA0LCJleHAiOjE2NjE3NzM1MDR9.dSKGRA8gL3b-w-lc089SwiMN29sMlLjT_jThIkbjCU0
Content-Type: application/json 

{
    "name": "Yoga Restaurativo",
    "time": "07:00",
    "teacher": "Louize",
    "capacity": 8,
    "changingDate": "05/04/2022"
}

// deleteClass
###
DELETE http://localhost:3003/calendar/5cdcedbd-5fd3-4ece-a027-840c1648d23b?allClasses=true
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzY5OTA0LCJleHAiOjE2NjE3NzM1MDR9.dSKGRA8gL3b-w-lc089SwiMN29sMlLjT_jThIkbjCU0


// changeCapacity
###
PUT  http://localhost:3003/calendar/changeCapacity/subtract/1324f4c1-5e8a-419d-b619-3a732bf984af
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzY5OTA0LCJleHAiOjE2NjE3NzM1MDR9.dSKGRA8gL3b-w-lc089SwiMN29sMlLjT_jThIkbjCU0
