// createCheckin
###
POST http://localhost:3003/booking
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxMjU0NDY3LCJleHAiOjE2NjEyNTgwNjd9.sRVm4GN3_moGzW9HqIqk_YKE95HtPrCoHb5DodJaEdg
Content-Type: application/json 

{
    "contractId": "0756c494-bbbf-46f8-bf12-34b5b1aa5564",
    "yogaClassId": "02f16a6d-5cb1-4aa7-ad0c-75212d23c3c2"     
}

// validadeCheckin
###
PUT http://localhost:3003/booking
Content-Type: application/json 

{
    "checkinId": "fac7990a-2e6e-452e-b491-ed37d3d95337+0afc546c-4465-4cc3-9d36-dafab0dcc2e4",
    "verified": true
}

// deleteCheckin
###
DELETE http://localhost:3003/booking/fac7990a-2e6e-452e-b491-ed37d3d95337+0afc546c-4465-4cc3-9d36-dafab0dcc2e4
Content-Type: application/json 




