// findAllPlans
###
GET http://localhost:3003/plans

// postPlan
###
POST http://localhost:3003/plans
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzczNTYyLCJleHAiOjE2NjE3NzcxNjJ9.h9ZkcCbIugsuCxc6m8noFCLvXSK8JgiUJPKzrL_PNfA
Content-Type: application/json 

{
    "type": "Semestral",
    "frequency": "3x",
    "availableClasses": 36,
    "durationInMonths": 3,
    "monthlyPayment": "R$ 199,00"
}

// editPlan
###
PUT http://localhost:3003/plans/1x-Semestral
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImEyMzhkZDA0Y2JhYTU4MGIzMDRjODgxZTFjMDA4ZWMyOGZiYmFkZGMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20veWdtLXRlc3RlcyIsImF1ZCI6InlnbS10ZXN0ZXMiLCJhdXRoX3RpbWUiOjE3MTQ2NTY2MjksInVzZXJfaWQiOiJmeHNhRkNmT2toVWpJUks0WGdXMmdoNndiY2UyIiwic3ViIjoiZnhzYUZDZk9raFVqSVJLNFhnVzJnaDZ3YmNlMiIsImlhdCI6MTcxNDY1NjYyOSwiZXhwIjoxNzE0NjYwMjI5LCJlbWFpbCI6ImFkbWludGVzdEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYWRtaW50ZXN0QGVtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.GHQrgytU3lis_cm8Cuzx9IKkBuJQSVS0qi4DhrMOr0R27MBnNrIhzSoyevBPDKS2mJhzmwBDWtK8OPCi5wgbBSntj808mA3A3bey5AzbnEaQF2HotGIjHVD5RYSsxa1jnb8qAwuqFdD46VEqcJPp-xI18SXBa0b53XjcG2SkNaVJ-FVXxSMIEMlmJedss-j_zHtrPxNEa0OBgJ1b823C1rtS8FQSDldhsVCmqxxy32sBbfCD_xdnDFA2IWXTt2V0_WMbTGVelGtuWY-MobNn3GJNlbeSHhCF-Jgx0RIEBK36WLOb9W3yHyLfMfTPWYDUL1t0AFMfXR6DKH6lU1YUWw
Content-Type: application/json 

{   
    
    "price": 150
 
}

// deletePlan
###
DELETE  http://localhost:3003/plans/3x-Semestral
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im9vVmVzNFBXeG1kVnlMcTFnNFdoUTZGNXFKNzIiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY5MzM1MTIyNiwiZXhwIjoxNjk0MjE1MjI2fQ.IusataDyVpM0z5yhrP-3f7K76csCfEKK8IDA0xQXiLM

