

###
GET http://localhost:3003/messages/welcomeMessage
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImJhNjI1OTZmNTJmNTJlZDQ0MDQ5Mzk2YmU3ZGYzNGQyYzY0ZjQ1M2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20veWdtLXRlc3RlcyIsImF1ZCI6InlnbS10ZXN0ZXMiLCJhdXRoX3RpbWUiOjE3MTE3MTIxMjMsInVzZXJfaWQiOiJvdlR2WFB4bGhGZUpxbXN1UDNLYWZwRTBDTWwxIiwic3ViIjoib3ZUdlhQeGxoRmVKcW1zdVAzS2FmcEUwQ01sMSIsImlhdCI6MTcxMTcxMjEyMywiZXhwIjoxNzExNzE1NzIzLCJlbWFpbCI6InJvZHJpZ29iYnVxdWVyYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJyb2RyaWdvYmJ1cXVlcmFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.11O6zZF1CApH0EGHFUWIQhDcCIi4jIGAANSe4mc4lxGk1_0PZxGHm2JvZW64zlw2ZU8QRLkMnYGAsAG7fkQ0ZWNx3n-1gE85Wbv3DtPY_FiJewEI1YUZnDlDStLoLLbXrWWs2Qo9ZwSLLqxAYpP-3T9ptXdu0N3njpWt_s4O1J87lfqmDiUyX4vGxvPybFT2WYzyNIi3NCs9XLJ9yqSTHvWvV7eHfkq8EdO3kTvhoNV49ykBL5Bs4LKo8LljsSFmTZHLIkmb6QP21JVIUBWfVodS8VMslNiAIj6sAFvxm73uZBk0TNYpejmU7jLPH8Z1OLi9SNbRyyeMk29QbTkM2A

