
// Rota Calendar

// findAllClasses
###
GET http://localhost:3003/calendar?today=true
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzY5OTA0LCJleHAiOjE2NjE3NzM1MDR9.dSKGRA8gL3b-w-lc089SwiMN29sMlLjT_jThIkbjCU0
// CreateClass
###
POST http://localhost:3003/calendar/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzY5OTA0LCJleHAiOjE2NjE3NzM1MDR9.dSKGRA8gL3b-w-lc089SwiMN29sMlLjT_jThIkbjCU0
Content-Type: application/json 

{
    "name": "Hatha Yoga",
    "date": "30/06/2022",
    "day": "Quinta",
    "time": "19:00",
    "capacity": 8,
    "teacher": "Rodrigo"           
}

// editClass
###
PUT http://localhost:3003/calendar/e739d3e6-f966-4895-bf86-a2fd98bbb7f5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzY5OTA0LCJleHAiOjE2NjE3NzM1MDR9.dSKGRA8gL3b-w-lc089SwiMN29sMlLjT_jThIkbjCU0
Content-Type: application/json 

{
    "name": "Yoga Restaurativo",
    "time": "07:00",
    "teacher": "Louize",
    "capacity": 8,
    "changingDate": "05/04/2022"
}

// deleteClass
###
DELETE http://localhost:3003/calendar/5cdcedbd-5fd3-4ece-a027-840c1648d23b?allClasses=true
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzY5OTA0LCJleHAiOjE2NjE3NzM1MDR9.dSKGRA8gL3b-w-lc089SwiMN29sMlLjT_jThIkbjCU0


// changeCapacity
###
PUT  http://localhost:3003/calendar/changeCapacity/subtract/1324f4c1-5e8a-419d-b619-3a732bf984af
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzY5OTA0LCJleHAiOjE2NjE3NzM1MDR9.dSKGRA8gL3b-w-lc089SwiMN29sMlLjT_jThIkbjCU0
