
// Rota Contracts

// findAllContracts
###
GET http://localhost:3003/contracts/list
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTY3NDE3NTcwNSwiZXhwIjoxNjc0MTc5MzA1LCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay1hM3Njc0B5Z20tY29udHJvbC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInN1YiI6ImZpcmViYXNlLWFkbWluc2RrLWEzc2NzQHlnbS1jb250cm9sLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwidWlkIjoiZDM1ZDkyZTAtNjdmYS00NzFkLTk2OTgtYmVhOGM1NWEzMWEzIiwiY2xhaW1zIjp7ImFkbWluIjpmYWxzZX19.pVAnWnifiR6mkj4d7YI9pr1pX6FV3ygerLamFo2gDoM1BkINFLlc1a7FK1X4g_1EUHgNuSnP8y23Nt2ebx-fQ2J38ZP6_zPGw1r46qX-7TchdHuaosfai-gsrRpYA89T9kr3iu9FJzqED_KyRMqe2eXtFIiUuILzhUproFQ9aNe31056uupztDSxIah2CMrR_IBSQLz2Ioyht5dhGkI8vDKGscggh58pTAAIy5GvU6FWutjDM4_aNq1eTAoxqlaexF40jk5-YzcuW5Bj-oNloo9jfHza4BqANY5h6mYPBXu5Le8PQrY1Jsp1NNud9A43o6jFcOCDwesKXRLvXfcGeQ
// createContract
###
POST http://localhost:3003/contracts
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxODU4OTcwLCJleHAiOjE2NjE4NjI1NzB9.iAeCU7E9vn_cwzjH8ug55w7oZMXYnNqzQQE4ZoYL-TA

{
    "email": "rodrigobbuquera2222@gmail.com",
    "name": "Rodrigo brezolin",
    "plan": "1x-Semestral",
    "date": "2022-03-01"
}

// deleteContract
###
DELETE http://localhost:3003/contracts/ffcb7e80-9bc0-4262-bc29-4b02584ed95f


// findContractbyId
###
GET  http://localhost:3003/contracts/e315977f-a467-4875-86b4-a60bda2621b2

// findConstract - proprui
###
GET http://localhost:3003/contracts/user


// addNewContract
###
PUT http://localhost:3003/contracts/addNew/1926d57b-904c-46df-ac80-2ff0346a35b4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxODU4OTcwLCJleHAiOjE2NjE4NjI1NzB9.iAeCU7E9vn_cwzjH8ug55w7oZMXYnNqzQQE4ZoYL-TA
Content-Type: application/json 

{
    "plan": "1x-Mensal",
    "date": "2023-01-01"       
}

// editContract
###
PUT http://localhost:3003/contracts/edit/1926d57b-904c-46df-ac80-2ff0346a35b4
Content-Type: application/json 

{
    "plan": "1x-Mensal",
    "date": "2023-01-07"       
}


// changeClasse
###
PUT http://localhost:3003/contracts/changeClasses/subtract/d35d92e0-67fa-471d-9698-bea8c55a31a3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InprZFVINzNRUmtmalhxemhuTmRLVUF2YzNWbTIiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYxNzc3NTM2LCJleHAiOjE2NjE3ODExMzZ9.XHwcpiVGBEquH2BbZPNEEmSnfqEldc4yBZg2yV29Azw
