
// Rota Contracts

// findAllContracts
###
GET http://localhost:3003/contracts/list
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRQWUNqNzZ0QTRYQ0dyd05WYTB3ajd4ajR6MzMiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjU4ODM5MjUwLCJleHAiOjE2NTg4NDI4NTB9.7M7jTwsPKasAOZN2fTPxh3oErXiZH0NSahfHIp__P9Q
// createContract
###
POST http://localhost:3003/contracts
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRQWUNqNzZ0QTRYQ0dyd05WYTB3ajd4ajR6MzMiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjU4NTMwMTAzLCJleHAiOjE2NTg1MzM3MDN9.G5A_bXVOioRDoBEYIzqB7DDoMwIO03I73HPFTEXE3E8

{
    "email": "rodrigobbuquera22223333222222222@gmail.com",
    "name": "Rodrigo brezolin",
    "plan": "1x-Semestral",
    "date": "20/03/2022"
}

// deleteContract
###
DELETE http://localhost:3003/contracts/ffcb7e80-9bc0-4262-bc29-4b02584ed95f


// findContractbyId
###
GET  http://localhost:3003/contracts/e315977f-a467-4875-86b4-a60bda2621b2

// findConstract - proprui
###
GET http://localhost:3003/contracts/user


// addNewContract
###
PUT http://localhost:3003/contracts/addNew/e315977f-a467-4875-86b4-a60bda2621b2
Content-Type: application/json 

{
    "plan": "1x-Mensal",
    "date": "05/04/2022"       
}

// editContract
###
PUT http://localhost:3003/contracts/edit/e315977f-a467-4875-86b4-a60bda2621b2
Content-Type: application/json 

{
    "plan": "1x-Mensal",
    "date": "05/04/2022"       
}
